"""Export the skill's project tokens without third-party dependencies."""
import argparse
import json
import re
from pathlib import Path


def load_tokens(path):
    data = json.loads(path.read_text(encoding="utf-8"))
    themes = data["colors"]
    if set(themes) != {"light", "dark"} or set(themes["light"]) != set(themes["dark"]):
        raise ValueError("Light/dark themes must expose identical color roles")
    for theme in themes.values():
        for role, value in theme.items():
            if not re.fullmatch(r"[a-z][a-z0-9_]*", role):
                raise ValueError(f"Invalid resource role: {role}")
            if not re.fullmatch(r"#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?", value):
                raise ValueError(f"Invalid color for {role}: {value}")
    for group in ("spacing", "font_size", "radius", "motion_ms", "layout"):
        if any(not isinstance(v, (int, float)) or isinstance(v, bool) or v <= 0 for v in data[group].values()):
            raise ValueError(f"{group} must contain positive numeric values")
    return data


def css_text(data):
    lines = ["/* Generated by scripts/export_tokens.py; edit design-tokens.json. */", ":root {", "  color-scheme: light;"]
    lines.append("  --h-font-family: " + data["font_family"] + ";")
    for role, value in data["colors"]["light"].items():
        lines.append(f"  --h-color-{role.replace('_', '-')}: {value};")
    for group in ("spacing", "font_size", "radius", "motion_ms", "layout"):
        for role, value in data[group].items():
            # Fonts use rem so browser text-size preferences remain effective.
            unit_value = f"{value / 16:g}rem" if group == "font_size" else f"{value:g}{'ms' if group == 'motion_ms' else 'px'}"
            lines.append(f"  --h-{group.replace('_', '-')}-{role.replace('_', '-')}: {unit_value};")
    lines += ["}", ':root[data-theme="dark"] {', "  color-scheme: dark;"]
    for role, value in data["colors"]["dark"].items():
        lines.append(f"  --h-color-{role.replace('_', '-')}: {value};")
    return "\n".join(lines + ["}", ""])


def arkui_color(value):
    return "#" + value[-2:] + value[1:7] if len(value) == 9 else value


def export(data, target, out):
    if target == "css":
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(css_text(data), encoding="utf-8")
        return [out]
    paths = []
    for theme, folder in (("light", "base"), ("dark", "dark")):
        path = out / folder / "element" / "color.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        colors = [{"name": "harmony_" + role, "value": arkui_color(value)} for role, value in data["colors"][theme].items()]
        path.write_text(json.dumps({"color": colors}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tokens", type=Path, default=Path(__file__).resolve().parents[1] / "assets" / "design-tokens.json")
    parser.add_argument("--target", choices=("css", "arkui-colors"), required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    for path in export(load_tokens(args.tokens), args.target, args.out):
        print(path)


if __name__ == "__main__":
    main()
