import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
export function configuration(mode) {
  if (!['baseline', 'notifications'].includes(mode)) throw new Error('Mode must be baseline or notifications');
  const manifest = JSON.parse(readFileSync(`${root}config/module.base.json`, 'utf8'));
  if (mode === 'notifications') {
    manifest.module.requestPermissions.push({ name: 'ohos.permission.SUBSCRIBE_NOTIFICATION' });
    manifest.module.extensionAbilities = [{
      name: 'NotificationSubscriberExtAbility',
      srcEntry: './ets/extensionability/NotificationSubscriberExtAbility.ets',
      type: 'notificationSubscriber',
      description: '$string:subscriber_desc',
      icon: '$media:app_icon',
      label: '$string:subscriber_label',
      exported: true
    }];
  }
  return {
    manifest: `${JSON.stringify(manifest, null, 2)}\n`,
    modeSource: `// Generated by scripts/configure-probe.mjs; do not edit by hand.\nexport const NOTIFICATION_PROBE_ENABLED: boolean = ${mode === 'notifications'};\n`
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2];
  const result = configuration(mode);
  mkdirSync(`${root}entry/src/main/ets/config`, { recursive: true });
  writeFileSync(`${root}entry/src/main/module.json5`, result.manifest);
  writeFileSync(`${root}entry/src/main/ets/config/ProbeMode.ets`, result.modeSource);
  console.log(`Configured ${mode}; local DevEco compilation/signing is still required.`);
}
